//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warzywniak.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class User
	{
		public int UserId { get; set; }
		[DisplayName("User Name:")]
		[Required(ErrorMessage ="This field is required.")]
		public string Nick { get; set; }
		[DisplayName("Password:")]
		[DataType(DataType.Password)]
		[Required(ErrorMessage = "This field is required.")]
		public string Password { get; set; }
		public int PhoneNumber { get; set; }
		public string EmailAddress { get; set; }

		public string LoginErrorMessage { get; set; }
	}
}
