//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warzywniak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int WarehouseId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
